version: '3.8'

services:
  pera-server:
    build:
      context: ./server
    ports:
      - "${PERA_SERVER_PORT}:${PERA_SERVER_PORT}"
    environment:
      - PORT=${PERA_SERVER_PORT}
    networks:
      - app-network
    volumes:
      - ./server:/app

  shard1:
    build:
      context: ./shard
    ports:
      - "${SHARD_1_PORT}:${SHARD_1_PORT}"
    environment:
      - SHARD_ID=1
      - PORT=${SHARD_1_PORT}
    networks:
      - app-network
    volumes:
      - ./shard:/app
  shard2:
    build:
      context: ./shard
    ports:
      - "${SHARD_2_PORT}:${SHARD_2_PORT}"
    environment:
      - SHARD_ID=2
      - PORT=${SHARD_2_PORT}
    networks:
      - app-network
    volumes:
      - ./shard:/app
  shard3:
    build:
      context: ./shard
    ports:
      - "${SHARD_3_PORT}:${SHARD_3_PORT}"
    environment:
      - SHARD_ID=3
      - PORT=${SHARD_3_PORT}
    networks:
      - app-network
    volumes:
      - ./shard:/app

networks:
  app-network:
    driver: bridge
